name: on_time_server
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.0

dependencies:
  args: ^2.4.0
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  dotenv: ^4.2.0
  postgres: ^3.2.1
  get_it: ^8.0.2
  drift_postgres: ^1.3.0
  drift: ^2.21.0
  uuid: ^4.4.0
  dart_jsonwebtoken: ^2.14.0
  collection: ^1.18.0
  shelf_web_socket: ^2.0.0
  web_socket_channel: ^3.0.1
  stream_channel: ^2.1.2
  mailer: ^6.2.0

dev_dependencies:
  http: ^1.1.0
  lints: ^5.0.0
  test: ^1.24.0
  very_good_analysis: ^6.0.0
  build_runner: ^2.4.10
  drift_dev: ^2.18.0